# Use an official Ubuntu as a parent image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Install OpenJDK 17 (or the latest version available in Ubuntu)
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk \
                       build-essential \
                       cmake \
                       git \
                       wget \
                       unzip \
                       maven \
                       libx11-dev \
                       libxfixes-dev \
                       libxext-dev \
                       libdrm-dev && \
    apt-get clean;

# Set the environment variable for Java library path
ENV LD_LIBRARY_PATH /usr/local/lib

# Copy the current directory contents into the container at /app
COPY . /app

# Compile the Maven project
# RUN mvn clean package

# Expose port 5005
# EXPOSE 5005

# Run the Java application
# CMD ["java", "-cp", "target/agora-example-1.0-SNAPSHOT.jar:target/lib", "com.example.Main"]
