# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jdk

# Set the working directory
WORKDIR /app

# Install necessary dependencies for Agora C++ SDK
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    unzip \
    maven

# Download and install Agora C++ SDK
RUN wget -qO- https://download.agora.io/rtsasdk/release/Agora-RTC-x86_64-linux-gnu-v4.2.30-20240202_172130-292462.tgz | tar xvz -C /opt && \
    cp -r /opt/agora_rtc_sdk/agora_sdk/* /usr/local/lib/ && \
    ldconfig

# Copy the current directory contents into the container at /app
COPY . /app

# Set the environment variable for Java library path
ENV LD_LIBRARY_PATH /usr/local/lib

# Compile the Maven project
RUN mvn clean package

# # Run the Java application
CMD ["java", "-cp", "target/agora-example-1.0-SNAPSHOT.jar", "com.example.Main"]
# CMD ["sh", "-c", "while :; do sleep 2073600; done"]
