# Use an official OpenJDK runtime as a parent image
FROM mcr.microsoft.com/devcontainers/java:1-21-bullseye

# Set the working directory
WORKDIR /app

# Install necessary dependencies for Agora C++ SDK
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    unzip \
    maven \
    libx11-dev \
    libxfixes-dev \
    libxext-dev \
    libdrm-dev \
    gdb && \
    wget -O /tmp/libhsdis-amd64.so https://chriswhocodes.com/hsdis/hsdis-amd64.so

    # Copy the current directory contents into the container at /app
COPY . /app
    
# Compile the Maven project
RUN cp /tmp/libhsdis-amd64.so $JAVA_HOME/lib/server && \
mvn dependency:get -Dartifact=io.agora.rtc:linux-sdk:3.7.200.21

RUN jar xf target/lib/linux-sdk-3.7.200.21.jar native
    
# Set the environment variable for Java library path
ENV LD_LIBRARY_PATH=/app/agora_rtc_sdk/agora_sdk:$LD_LIBRARY_PATH

RUN ldconfig

EXPOSE 5005
# # Run the Java application
# CMD ["java", "-cp", "target/agora-example-1.0-SNAPSHOT.jar:target/lib", "com.example.Main"]
# CMD ["sh", "-c", "while :; do sleep 2073600; done"]
